---
# tasks file for vector-role

- name: Copy Vector distribution from local machine
  ansible.builtin.copy:
    src: "{{ local_vector_file }}"
    dest: "/tmp/vector.deb"
    mode: '0755'

- name: Ensure the extraction directory exists
  ansible.builtin.file:
    path: /usr/local/vector/
    state: directory
    mode: '0755'
  become: true

- name: Install Vector package
  ansible.builtin.apt:
    deb: "/tmp/vector.deb"
    state: present
  become: true

- name: Ensure the configuration directory exists
  ansible.builtin.file:
    path: /etc/vector/
    state: directory
    mode: '0755'
  become: true

- name: Restart Vector service after installation
  ansible.builtin.service:
    name: vector
    state: restarted
  become: true
